apiVersion: v1
kind: ReplicationController

metadata:
    name: fe-test-rc
    labels:
        app: test-app
        type: frontend
spec:
  template:
    metadata:
      name: fe-test-pod
      labels:
        app: test-app
        type: frontend
    spec:
      containers:
        - name: fe-test-container
          image: nginx:1.14.2
  replicas: 5
